### ISSUE TITLE
Automatically grab API key from WaniKani

### ISSUE THREAD

**Issue by mcaubrey** [oguzgelal/juken#34]
To be honest I'm not sure how you'd go about implementing this, but I think the other WaniKani iOS solution I tried automatically grabbed my API key somehow if I was already logged into WaniKani on my browser. Maybe look into how you could do this?

**Comment by oguzgelal** [comment]
Juken do persist your token once you enter it, but I don't see how "grabbing it" would be technically possible. Because it's not an "api key" that's associated with users account, it's a personalized token that user _generates_ for an individual application, customizing the permissions they want to give to the app. So before user generates the token for Juken, it doesn't exist.

I'll close this for now, but if you remember that WaniKani iOS app you mentioned, I'm happy to investigate.
