### ISSUE TITLE
Ordering of reviews

### ISSUE THREAD

**Issue by syne-** [oguzgelal/juken#72]
Instead of always having a random order it would be nice to have some alternatives.
For example "longest available" or "lowest SRS stage" to be able to do the more important ones first in case you don't have time to do all reviews at once.

**Comment by rafascar** [comment]
Hello @oguzgelal, hope you are doing fine! 
Just tried my hand at implementing a `Review Order` option #85.
It would be wonderful if you could take a look, and any feedback is highly appreciated 😄  (especially since I'm a back-end developer so not sure what the best-practices here!)
Cheers mate, congrats on your app btw, it's awesome!

**Comment by ghost** [comment]
I’ll close this since this has been merged
